=== sam-stewart/oosd/xml/student.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="student">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="course" maxOccurs="8">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="title" type="xs:string"/>
              <xs:element name="description" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required"/>
            <xs:attribute name="startdate" type="xs:date" use="required"/>
            <xs:attribute name="enddate" type="xs:date" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="id" type="xs:int" use="required"/>
      <xs:attribute name="firstname" type="xs:string" use="required"/>
      <xs:attribute name="lastname" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== sam-stewart/oosd/xml/student.xml
<?xml version = "1.0"?>

<student id="11005725" firstname="Sam" lastname="Stewart"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="student.xsd">
    <course id="in700002" startdate="2015-07-20" enddate="2015-11-20">
        <title>Project 2</title>
        <description>Fun times</description>
    </course>
    <course id="in705001" startdate="2015-07-20" enddate="2015-11-20">
        <title>Databases 3</title>
        <description>New machine learning stuff</description>
    </course>
    <course id="in711001" startdate="2015-07-20" enddate="2015-11-20">
        <title>Algorithms and Data Structures</title>
        <description>Cool things</description>
    </course>
    <course id="in700001" startdate="2015-02-16" enddate="2015-06-26">
        <title>Project 1</title>
        <description>Sam Mann's holiday time</description>
    </course>
    <course id="in710001" startdate="2015-02-16" enddate="2015-06-26">
        <title>OO Systems Development</title>
        <description>Gang of four</description>
    </course>
    <course id="in719001" startdate="2015-02-16" enddate="2015-06-26">
        <title>Systems Administration</title>
        <description>Puppet heaven</description>
    </course>
    <course id="in721000" startdate="2015-02-16" enddate="2015-06-26">
        <title>Mobile Development</title>
        <description>Design and development of applications for mobile devices</description>
    </course>
</student>
